### ISSUE TITLE
statement: Column Statistic Interval

### ISSUE THREAD

**Issue by bressanmarcos** [bigdatabr/deirokay#21]
This statement evaluates whether or not a given column statistic falls within an interval.

Usage:

```yaml
type: column_statistic
statistic: mean  # / mode / max / min / median
greater_than: 80
greater_or_equal_to: 50
equal_to: 100
lesser_or_equal_to: 110
lesser_than: 150
```

or even:

```yaml
type: statistic_interval
statistic: mean  # / mode / max / min / median
'>': 80
'>=': 50
'=': 100
'<=': 110
'<': 150
```
