### ISSUE TITLE
Extra scoping abilities to filter df by column value before sending to statement evaluation 

### ISSUE THREAD

**Issue by bressanmarcos** [bigdatabr/deirokay#22]
Scope could do more than simply filter columns, it could filter rows as in a Sql "where" clause.

This would make any statement work exactly how it does currently, but also provide extra scoping abilities to Deirokay.

Tip: pandas built-in `df.query` method.

Usage example:

```yaml
scope: 
  - age,
  - where: "name = 'john'"
  - where: "age >= 30"
statements: [ ... ]
```
